In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
# 1D array
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [6]:
#2D array

my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [30]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.random.rand(5)

array([0.26213955, 0.30151808, 0.19389767, 0.13231511, 0.41749069])

In [35]:
np.random.randn(4,5)

array([[-1.22173134,  0.14883975, -0.13887151,  0.15790733,  1.44784929],
       [ 0.99260235,  0.67046422, -1.38385558,  1.31815374, -0.42032416],
       [-0.828919  ,  0.90103591, -0.4625667 ,  0.44534289, -0.85805544],
       [ 1.55784948, -0.46712651,  0.35363308, -2.06557093, -1.66530344]])

In [61]:
np.random.randint(2,5,10)

array([4, 2, 4, 2, 2, 3, 3, 2, 4, 2])

In [65]:
arr = np.arange(0,25)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
ranarr = np.random.randint(0,50,10)

In [76]:
ranarr

array([ 6, 44, 23, 17, 17, 38,  9, 28,  9, 33])

In [80]:
ranarr.max()

44

In [82]:
ranarr.min()

6

In [84]:
ranarr.argmax()

1

In [86]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
arr.shape

(25,)

In [91]:
arr.dtype

dtype('int32')

In [97]:
# retriving values from 2D array

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [99]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
arr_2d[1][2]

6

In [103]:
arr_2d[1,2]

6

In [106]:
#Retrieve som part of matrix like sub martrix
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [108]:
#conditional statement
arr = np.arange(1,11)

In [110]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr[arr>5]5

array([ 6,  7,  8,  9, 10])

In [115]:
boolean = arr>5

In [118]:
arr[boolean]

array([ 6,  7,  8,  9, 10])

In [120]:
boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [130]:
arr_2d = np.arange(50).reshape(5,10)

In [138]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [139]:
# get subset from above matrix

arr_2d[:3,4:]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [140]:
# Numpy Operations

In [147]:
#Array with array

arr = np.arange(0,11)

In [149]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [153]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [158]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [160]:
# Array with scalars (add's 100 to each number in element)
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [161]:
# Numpy Exercises

import numpy as np

In [163]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [165]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [167]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [169]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [171]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [178]:
# matrix from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [180]:
#identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [188]:
#generate random number between o and 1
np.random.rand(1)

array([0.15621125])

In [189]:
# Excercises from W3 resource website

In [193]:
#numpy version
import numpy as np

print(np.__version__)
print(np.show_config())

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/suppuletix067037/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/suppuletix067037/AppData/Local/Continuum/anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/suppuletix067037/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

In [196]:
# information of add function

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [205]:
# Test if any of the elements of array is Zero - all method

arr = np.array([1,2,3,4,5])
arr1 = np.array([0,1,2,3,4])
print(np.all(arr))
print(np.all(arr1))

True
False


In [208]:
# Test if any elements of array are non zero - any method
arr_zero = np.array([0,1,0,0,0])
np.any(arr_zero)

True

In [211]:
# compare two arrays to check for greater values
x = np.array([1,3])
y = np.array([3,2])
print(np.greater(x,y))

[False  True]


In [213]:
# compare two arrays to check for lesser values
print(np.less(x,y))

[ True False]


In [225]:
# size of array in bytes
arr_size = np.array([1,7,13,105])
print(arr_size.size)
print(np.size(arr_size))
print("Size in bytes")
print(arr_size.size * arr_size.itemsize)

4
4
Size in bytes
16


In [227]:
np.info(arr_size.itemsize)

int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4


In [238]:
# Numpy program to create 10 zeros, ones and fives

print(np.zeros(10))
print(np.ones(10))
print(np.zeros(10) + 5 ) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [240]:
# create array of integers from 30 to 70

arr = np.arange(30,71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [242]:
# create array of  even integers from 30 to 70
arr = np.arange(30,71,2)
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [247]:
# Write a NumPy program to create a 3x3 identity matrix.

arr_iden = np.eye(3,3)
arr_iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [253]:
# Write a NumPy program to generate a random number between 0 and 1

arr_ran = np.random.randn(1)
arr_ran


array([-0.87151426])

In [267]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

arr_ran = np.random.rand(15)
arr_ran

array([0.73363167, 0.2915254 , 0.02588222, 0.55063551, 0.62627768,
       0.28758184, 0.02339359, 0.91148313, 0.1784574 , 0.16835209,
       0.106073  , 0.75007743, 0.0780144 , 0.34493901, 0.74113089])

In [276]:
# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last. 

arr = np.arange(15,55)
print(arr)
print(arr[1:])


[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [286]:
# Write a NumPy program to create a 3X4 array using and iterate over it.

arr = np.arange(0,12).reshape((3,4))
print (arr)
print("Iterating the matrix")
for i in np.nditer(arr):
    print (i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Iterating the matrix
0
1
2
3
4
5
6
7
8
9
10
11


In [290]:
# Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50
arr = np.linspace(10,5,51)
arr


array([10. ,  9.9,  9.8,  9.7,  9.6,  9.5,  9.4,  9.3,  9.2,  9.1,  9. ,
        8.9,  8.8,  8.7,  8.6,  8.5,  8.4,  8.3,  8.2,  8.1,  8. ,  7.9,
        7.8,  7.7,  7.6,  7.5,  7.4,  7.3,  7.2,  7.1,  7. ,  6.9,  6.8,
        6.7,  6.6,  6.5,  6.4,  6.3,  6.2,  6.1,  6. ,  5.9,  5.8,  5.7,
        5.6,  5.5,  5.4,  5.3,  5.2,  5.1,  5. ])

In [303]:
# Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

arr = np.arange(0,21)
print(arr)
arr[(arr>8) & (arr<=15) ] *= -1
arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [306]:
# Write a NumPy program to multiply the values of two given vectors.

x = np.array([1,4,2,6])
y = np.array([2,7,4,1])
print(x)
print(y)
print (x * y)

[1 4 2 6]
[2 7 4 1]
[ 2 28  8  6]


In [309]:
# Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21. 

arr = np.arange(10,22).reshape((3,4))
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [324]:
# Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

arr = np.ones((10,10))
print(arr)
print ('\n')
arr[1:9,1:9] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [333]:
# Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4,

arr = np.diag([1,2,3,4,5,6])
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [334]:
# Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

np.random.random((3,3,3))

array([[[0.29621139, 0.43583449, 0.12981178],
        [0.01102259, 0.53303166, 0.03859737],
        [0.94260582, 0.87807723, 0.49633267]],

       [[0.69904499, 0.57233202, 0.65035959],
        [0.80724106, 0.81920178, 0.28941823],
        [0.3522501 , 0.74582097, 0.12451286]],

       [[0.36270052, 0.65860375, 0.03566409],
        [0.02956051, 0.0796272 , 0.6021729 ],
        [0.24725043, 0.0860292 , 0.93653994]]])

In [336]:
# Write a NumPy program to compute the inner product of two given vectors.

x = np.array([2,3])
y = np.array([4,5])
print(x)
print(y)
print('Inner product of two vectors')
np.dot(x,y)

[2 3]
[4 5]
Inner product of two vectors


23

In [344]:
# Write a NumPy program to add a vector to each row of a given matrix. 
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print(m)
print('/n')
print(v)
result = np.empty_like(m)
print(result)
for i in range(4):
    result[i,:] = m[i,:] + v
print (result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
/n
[1 1 0]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]
