In [8]:
# Write a NumPy program to compute the multiplication of two given matrixes
import numpy as np
a = [[1,2],[3,4]]
b = [[4,3],[2,1]]
print(a)
print(b)
result = np.dot(a,b)
print(result)

[[1, 2], [3, 4]]
[[4, 3], [2, 1]]
[[ 8  5]
 [20 13]]


In [24]:
# Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.
a = np.array([[2,1],[4,3]])
print(a)
print(np.sort(a))
print(np.sort(a,axis=0))
print("\n Flattened array")
print(np.sort(a,axis=None))

[[2 1]
 [4 3]]
[[1 2]
 [3 4]]
[[2 1]
 [4 3]]

 Flattened array
[1 2 3 4]


In [37]:
# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

data_type = [('name','S15'),('class','int'),('height','float')]
student_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
print(data_type)
print(student_details)
students = np.array(student_details, dtype = data_type )
print("\nOrignal Array: ")
print(students)
print("\n After Sorting")
print(np.sort(students, order = 'height'))


[('name', 'S15'), ('class', 'int'), ('height', 'float')]
[('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.1), ('Pit', 5, 40.11)]

Orignal Array: 
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]

 After Sorting
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [48]:
# Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
# sort by student id and then student height
indices = np.lexsort((student_id,student_height))
print(indices)
for i in indices:
    print(student_id[i],student_height[i])

[4 0 5 3 6 1 2]
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


In [50]:
# Write a NumPy program to get the indices of the sorted elements of a given array. Go to the editor

a = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original Arary: ")
print(a)
print("Sorted Array: ")
res = np.argsort(a)
print(res)

Original Arary: 
[1023 5202 6230 1671 1682 5241 4532]
Sorted Array: 
[0 3 4 6 1 5 2]


In [67]:
nums = np.random.rand(10)
print(nums)
print(nums[np.argpartition(nums,range(5))])

[0.33601938 0.42252099 0.92055825 0.28077033 0.32945027 0.95037386
 0.94648518 0.74728426 0.47535096 0.9811908 ]
[0.28077033 0.32945027 0.33601938 0.42252099 0.47535096 0.95037386
 0.94648518 0.74728426 0.92055825 0.9811908 ]
