In [3]:
# Write a NumPy program to print the NumPy version in your system

import numpy as np

print(np.__version__)

1.15.4


In [5]:
# Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

l = [1,2,3,4]
print(l)
print(np.array(l))

[1, 2, 3, 4]
[1 2 3 4]


In [7]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

arr = np.arange(2,11).reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [10]:
# Write a NumPy program to create a null vector of size 10 and update sixth value to 11.
arr = np.zeros(10)
arr
arr[6] = 11
arr

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [13]:
#Write a NumPy program to create a array with values ranging from 12 to 38.

arr = np.arange(12,39)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [28]:
#Write a NumPy program to reverse an array (first element becomes last).
arr
print(arr[::-1])

[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [34]:
# Write a NumPy program to create a 2d array with 1 on the border and 0 inside

x = np.ones((5,5))
x[1:4,1:4]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
# Write a NumPy program to add a border (filled with 0's) around an existing array.
x = np.ones((3,3))
x=np.pad(x,pad_width=1, mode= 'constant',constant_values =0 )
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
#  Write a NumPy program to convert a list and tuple into arrays
l = [1,2,3]
t = ([1,2,3],[4,5,6])
print("list: ",l)
print("Tuple: ",t)
x=np.asarray(l)
y=np.asarray(t)
print("list->array",x)
print("Tuple->array",y)

list:  [1, 2, 3]
Tuple:  ([1, 2, 3], [4, 5, 6])
list->array [1 2 3]
Tuple->array [[1 2 3]
 [4 5 6]]


In [53]:
#  Write a NumPy program to append values to the end of an array
x=[10,20,30]
x = np.append(x,[40,50,60,70])
print(x)


[10 20 30 40 50 60 70]


In [66]:
# Write a NumPy program to create an empty and a full array
x = np.empty((3,4))
print(x)
y = np.full((3,3),6)
print(y)

[[0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [75]:
# Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

x = np.arange(0,4)
print (x)
print("number of elements",x.size)
print("length of array elements in bytes",x.itemsize)
print("Total bytes consumed by array",x.nbytes)

[0 1 2 3]
number of elements 4
length of array elements in bytes 4
Total bytes consumed by array 16


In [77]:
# Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

arr1 = [1,2,3,4]
arr2 = [1,4,6,8]
print(np.in1d(arr1,arr2))

[ True False False  True]


In [79]:
# Write a NumPy program to find common values between two arrays

arr1 = [1,2,3,4]
arr2 = [1,4,6,8]
print(np.intersect1d(arr1,arr2))

[1 4]


In [82]:
# Write a NumPy program to get the unique elements of an array

arr = [1,1,2,3,3,4,4,6]
np.unique(arr)

array([1, 2, 3, 4, 6])

In [85]:
# Write a NumPy program to construct an array by repeating

arr = [1,4,3]
print(np.tile(arr,2))

[1 4 3 1 4 3]


In [4]:
# Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array

x = [0,1,2,3,4]
print("max of array:",np.argmax(x))
print("min of array: ",np.argmin(x))

max of array: 4
min of array:  0


In [9]:
# Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

x=np.array([[0,10,20],[30,40,50]])
print (x[x>10])

[20 30 40 50]


In [12]:
# Flattened array

x = np.array([[10, 20, 30], [20, 40, 50]])
print ("original array: ",x)
print("Flattened array: ",np.ravel(x))

original array:  [[10 20 30]
 [20 40 50]]
Flattened array:  [10 20 30 20 40 50]


In [16]:
# Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

x = np.diagflat([4,5,6,8])
print(x)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [19]:
# Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50. 

x = np.arange(0,51)
print(x)
y = np.arange(10,51)
print(y)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [26]:
# Write a NumPy program to create an array which looks like below array. 

x=np.zeros((4,3))
x[1:-1,1:]=1

print(x)


[[0. 0. 0.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 0. 0.]]


In [29]:
# Fourth element of array
x = np.array([[2, 4, 6], [6, 8, 10]])
print(x)
print(x.flat[3])

[[ 2  4  6]
 [ 6  8 10]]
6


In [36]:
# Write a NumPy program to interchange two axes of an array.
x = np.array([[1,2,3]])
print(x)
y = np.swapaxes(x,0,1)
print(y)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [40]:
x = np.zeros((3, 1, 4))
print(x)
print(np.squeeze(x))
print(np.squeeze(x).shape)

[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


In [61]:
# Split array horizontally

x = np.arange(16).reshape((4, 4))
print(x)
print(np.hsplit(x,[3,0]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([], shape=(4, 0), dtype=int32), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [67]:
# count number of non zeros
x = np.array([[0,10,20],[30,40,0]])
print(x)
print("number of non zeros: ",np.count_nonzero(x))

[[ 0 10 20]
 [30 40  0]]
number of non zeros:  4


In [71]:
# Write a NumPy program to make an array immutable (read-only)

x = np.zeros(10)
x.flags.writeable = False
print(x)

x[2] = 3

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

In [78]:
# Write a NumPy program to create and display every element of an numpy array.
x = np.arange(12).reshape(3, 4)
print(x)
for i in np.nditer(x):
    print(i , end = ' ')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 4 5 6 7 8 9 10 11 

In [82]:
# add column to the existing array

x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x,y,axis = 1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [84]:
# Write a NumPy program to remove specific elements in a numpy array.
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index = [0,4,6]
y=np.delete(x,index)
print(y)

[ 20  30  40  60  80  90 100]


In [92]:
# Write a NumPy program to remove the negative values in a numpy array with 0

x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("original array: ",x)
x[x<0] = 0
print("result after replacing negative value: ",x)

original array:  [-1 -4  0  2  3  4  5 -6]
result after replacing negative value:  [0 0 0 2 3 4 5 0]


In [97]:
# count unique elements of array 
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print(np.unique(a))
print(np.unique(a,return_counts = True))

[10 20 30 40 50]
(array([10, 20, 30, 40, 50]), array([3, 4, 2, 2, 1], dtype=int64))


In [100]:
# Write a NumPy program to check whether the numpy array is empty or not. 
a = np.array([1,2,3])
b = np.array([])
print(a.size)
print(b.size)

3
0


In [112]:
# Write a NumPy program to divide each row by a vector element. 
x = np.array([[20,20,20],[30,30,30],[40,40,40]])
print("Original array:")
print(x)
v = np.array([20,30,40])
print("Vector:")
print(v)
print(x / v[:,None])

Original array:
[[20 20 20]
 [30 30 30]
 [40 40 40]]
Vector:
[20 30 40]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [117]:
#  Write a NumPy program to sum and compute the product of a numpy array elements.
a = np.array([10,20,30])
print("sum: ", a.sum())
print("Product: ",a.prod())

sum:  60
Product:  6000


In [125]:
# Write a NumPy program to take values from a source array and put them at specified indices of another array.

a = np.array([10,20,30,40,50,60])
b = np.array([70,80,90])
a.put([0,4],b)
print(a)

[70 20 30 40 80 60]


In [127]:
# Write a NumPy program to calculate the Euclidean distance.

from scipy.spatial import distance

p1 = (1,2,3)
p2 = (4,5,6)
d = distance.euclidean(p1,p2)
print(d)

5.196152422706632


In [137]:
# Write a NumPy program to access last two columns of a multidimensional columns.
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
result = a[:,[1,2]]
print(result)
print(a[:,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [144]:
# Write a NumPy program to count the occurrence of a specified item in a given NumPy array.

a = np.array([10,10,20,30,40,20,20,30,30,50,60,70,60,60,50,50])
print(np.unique(a,return_counts = True))
print(np.count_nonzero(a==10))
print(np.count_nonzero(a==20))
print(np.count_nonzero(a==30))
print(np.count_nonzero(a==40))
print(np.count_nonzero(a==50))
print(np.count_nonzero(a==60))
print(np.count_nonzero(a==70))

(array([10, 20, 30, 40, 50, 60, 70]), array([2, 3, 3, 1, 3, 3, 1], dtype=int64))
2
3
3
1
3
3
1


In [160]:
#Write a NumPy program to convert a numpy array to an image. Display the image.

from PIL import Image
import numpy as np

img_w,img_h = 300,500
data = np.zeros((img_w,img_h,3))
#data[100,100]=[255,0,0]
img = Image.fromarray(data, 'RGB')
#img.save('test.png')
img.show()

In [168]:
# Write a NumPy program to create random set of rows from 2D array.

a = np.random.randint(10,size=(5,4))
print(a)

[[3 0 5 2]
 [1 2 0 6]
 [2 6 2 8]
 [3 8 9 3]
 [4 6 2 3]]


In [175]:
# Write a NumPy program to find indices of elements equal to zero in a numpy array.
a = np.array([1,4,3,45,0,6,1,0,3,0])
result = np.where(a==0)[0]
print("original array: ",a)
print("Indices of zeros's in array: ", result)

original array:  [ 1  4  3 45  0  6  1  0  3  0]
Indices of zeros's in array:  [4 7 9]


In [193]:
# Write a NumPy program to add a new row to an empty numpy array.
a = np.empty((0,3),int)
print("Empty Array: ")
print(a)
print("After first row added: ")
a = np.append(a,np.array([[10,20,30]]),axis =0)
print(a)
print("After second row added: ")
a = np.append(a,np.array([[40,50,60]]),axis =0)
print(a)

Empty Array: 
[]
After first row added: 
[[10 20 30]]
After second row added: 
[[10 20 30]
 [40 50 60]]


In [198]:
# Write a NumPy program to broadcast on different shapes of arrays where a(,3) + b(3).
a = np.array([[10],[20],[30]])
b = np.array([1,2,3])
print(a)
print(b)
res = a + b
print("result:",res)

[[10]
 [20]
 [30]]
[1 2 3]
result: [[11 12 13]
 [21 22 23]
 [31 32 33]]


In [202]:
# Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)
b = np.array([10,20,30])
print(a+b)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 20  40  60]
 [ 50  70  90]
 [ 80 100 120]]


In [206]:
# Write a NumPy program to rearrange the dimensions of a given array

a = np.arange(24).reshape(4,6)
print(a)
res = np.transpose(a)
print(res)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [219]:
# Write a NumPy program to stack arrays in sequence horizontally (column wise).

a = np.arange(9).reshape(3,3)
print(a)
b= np.arange(12).reshape(3,4)
print(b)
res = np.hstack((a,b))
print("\n")
print(res)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  0  1  2  3]
 [ 3  4  5  4  5  6  7]
 [ 6  7  8  8  9 10 11]]


In [232]:
# Write a NumPy program to create an array that represents the rank of each item of a given array.
a = np.array([4,56,12,34,78,65])
print("Original Array: ")
print(a)
a_argsort = a.argsort()
a_rank = np.empty_like(a_argsort)
print(a_argsort)
print(a_rank)
a_rank[a_argsort]=np.arange(len(a))
print("Rank of array: ")
print(a_rank)

Original Array: 
[ 4 56 12 34 78 65]
[0 2 3 1 5 4]
[0 2 3 1 5 4]
Rank of array: 
[0 3 1 2 5 4]


In [240]:
# Write a NumPy program to copy data from a given array to another array.
a = np.array([0,1,2,3,4])
b= np.empty_like(a)
b[:] = a
print(b)

[0 1 2 3 4]
